/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MeetOptixRouteImport } from './routes/meet-optix'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetOptixRoute = MeetOptixRouteImport.update({
  id: '/meet-optix',
  path: '/meet-optix',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/admin/knowledge',
  path: '/admin/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRoute
  '/meet-optix': typeof MeetOptixRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRoute
  '/meet-optix': typeof MeetOptixRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRoute
  '/meet-optix': typeof MeetOptixRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/home'
    | '/meet-optix'
    | '/register'
    | '/upload'
    | '/admin/knowledge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/home'
    | '/meet-optix'
    | '/register'
    | '/upload'
    | '/admin/knowledge'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/home'
    | '/meet-optix'
    | '/register'
    | '/upload'
    | '/admin/knowledge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  HomeRoute: typeof HomeRoute
  MeetOptixRoute: typeof MeetOptixRoute
  RegisterRoute: typeof RegisterRoute
  UploadRoute: typeof UploadRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-optix': {
      id: '/meet-optix'
      path: '/meet-optix'
      fullPath: '/meet-optix'
      preLoaderRoute: typeof MeetOptixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/admin/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  HomeRoute: HomeRoute,
  MeetOptixRoute: MeetOptixRoute,
  RegisterRoute: RegisterRoute,
  UploadRoute: UploadRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
